# Generated by Django 3.2.7 on 2021-09-26 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=200, unique=True)),
                ('calender', models.DateField(verbose_name='date to travel')),
                ('bio', models.TextField(max_length=2500)),
                ('release_date', models.DateField(verbose_name='date released')),
                ('review', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
